package com.example.ui.localization

enum class AppLanguage(val code: String, val label: String, val flag: String) {
    ENGLISH("en", "English", "EN"),
    BENGALI("bn", "বাংলা", "বাং")
}

data class DistroStrings(
    // App Bar
    val appTitle: String,
    val subtitle: String,
    val quickSync: String,
    val syncSuccess: String,
    val syncing: String,
    val lastSynced: String,

    // Navigation
    val navDashboard: String,
    val navSales: String,
    val navPurchase: String,
    val navProducts: String,
    val navReports: String,

    // Dashboard Overview
    val totalSales: String,
    val vsLastMonth: String,
    val customerDue: String,
    val supplierDue: String,
    val salesReturn: String,
    val supplierReturn: String,
    val totalExpense: String,
    val currentStockValue: String,
    val quickShortcuts: String,
    val recentInvoices: String,
    val viewAll: String,

    // Quick Action shortcuts
    val actionCustomer: String,
    val actionSupplier: String,
    val actionReturn: String,
    val actionExpense: String,
    val actionSales: String,
    val actionPurchase: String,
    val actionProducts: String,
    val actionReports: String,
    val actionRoutes: String,
    val actionThermalPrinter: String,

    // Sales Module
    val salesAndBilling: String,
    val newSaleBtn: String,
    val exportPdf: String,
    val searchSalePlaceholder: String,
    val filterAll: String,
    val filterToday: String,
    val filterThisMonth: String,
    val filterThisYear: String,
    val filterDue: String,
    val filterPaid: String,
    val invoiceNumber: String,
    val customerName: String,
    val items: String,
    val totalAmount: String,
    val paidAmount: String,
    val dueAmount: String,
    val invoiceCount: String,
    val statusPaid: String,
    val statusDue: String,
    val statusPartial: String,

    // Delivery Status
    val deliveryStatus: String,
    val stageTaken: String,
    val stagePacked: String,
    val stageInTransit: String,
    val stageDelivered: String,
    val markNextDeliveryStage: String,

    // Purchase Module
    val purchaseManagement: String,
    val newPurchaseBtn: String,
    val searchPurchasePlaceholder: String,
    val supplierName: String,
    val purchaseCount: String,

    // Product & Inventory
    val productInventory: String,
    val addProductBtn: String,
    val searchProductPlaceholder: String,
    val filterHighStock: String,
    val filterLowStock: String,
    val filterOnlyLow: String,
    val totalProducts: String,
    val stockQuantity: String,
    val totalBuyValue: String,
    val totalSaleValue: String,
    val skuBarcode: String,
    val unit: String,
    val buyPrice: String,
    val sellPrice: String,
    val margin: String,
    val stockAlertLow: String,
    val stockAlertOk: String,

    // Routes & Sales Reps
    val routeAreaManagement: String,
    val addRouteBtn: String,
    val assignedRep: String,
    val assignedShops: String,
    val pendingDeliveries: String,
    val repPhone: String,
    val activeRepStatus: String,

    // Thermal Receipt
    val thermalReceiptTitle: String,
    val printBluetooth: String,
    val shareInvoice: String,
    val printingSimulation: String,
    val printerConnected: String,
    val cashReceived: String,
    val changeAmount: String,
    val paymentMode: String,
    val thankyouNote: String,
    val taxVat: String,
    val subtotal: String,
    val discount: String,
    val grandTotal: String,

    // Common / Dialogs
    val cancel: String,
    val save: String,
    val close: String,
    val selectCustomer: String,
    val selectSupplier: String,
    val selectProduct: String,
    val quantity: String,
    val rate: String,
    val addLineItem: String,
    val currencySymbol: String
)

val EnglishStrings = DistroStrings(
    appTitle = "DistroMaster",
    subtitle = "Wholesale & Distribution",
    quickSync = "Sync Cloud",
    syncSuccess = "All data synchronized!",
    syncing = "Syncing with cloud...",
    lastSynced = "Synced just now",

    navDashboard = "Dashboard",
    navSales = "Sales",
    navPurchase = "Purchase",
    navProducts = "Products",
    navReports = "Reports",

    totalSales = "Total Sales",
    vsLastMonth = "+14.8% vs last month",
    customerDue = "Customer Due",
    supplierDue = "Supplier Due",
    salesReturn = "Sales Return",
    supplierReturn = "Supplier Return",
    totalExpense = "Total Expense",
    currentStockValue = "Current Stock Value",
    quickShortcuts = "Quick Access",
    recentInvoices = "Recent Invoices",
    viewAll = "View All",

    actionCustomer = "Customers",
    actionSupplier = "Suppliers",
    actionReturn = "Returns",
    actionExpense = "Expenses",
    actionSales = "Sales",
    actionPurchase = "Purchase",
    actionProducts = "Products",
    actionReports = "Reports",
    actionRoutes = "Routes & Reps",
    actionThermalPrinter = "Thermal Receipt",

    salesAndBilling = "Sales & Distribution Billing",
    newSaleBtn = "New Sale +",
    exportPdf = "Export PDF",
    searchSalePlaceholder = "Search by Invoice, Customer or Phone...",
    filterAll = "All Invoices",
    filterToday = "Today",
    filterThisMonth = "This Month",
    filterThisYear = "This Year",
    filterDue = "Due Only",
    filterPaid = "Paid",
    invoiceNumber = "Invoice #",
    customerName = "Customer / Store",
    items = "Items",
    totalAmount = "Total Amount",
    paidAmount = "Paid Amount",
    dueAmount = "Due Amount",
    invoiceCount = "Total Invoices",
    statusPaid = "PAID",
    statusDue = "DUE",
    statusPartial = "PARTIAL",

    deliveryStatus = "Delivery Status",
    stageTaken = "Order Taken",
    stagePacked = "Packed",
    stageInTransit = "In Transit",
    stageDelivered = "Delivered",
    markNextDeliveryStage = "Advance Status",

    purchaseManagement = "Purchases & Suppliers",
    newPurchaseBtn = "New Purchase +",
    searchPurchasePlaceholder = "Search supplier, purchase ref...",
    supplierName = "Supplier Name",
    purchaseCount = "Purchases Count",

    productInventory = "Products & Inventory",
    addProductBtn = "Add Product +",
    searchProductPlaceholder = "Search product name or SKU/barcode...",
    filterHighStock = "High Stock",
    filterLowStock = "Low Stock",
    filterOnlyLow = "Only Low",
    totalProducts = "Total SKUs",
    stockQuantity = "Total Stock Qty",
    totalBuyValue = "Total Buy Value",
    totalSaleValue = "Total Sale Value",
    skuBarcode = "SKU / Barcode",
    unit = "Unit",
    buyPrice = "Buy Rate",
    sellPrice = "Sell Rate",
    margin = "Margin",
    stockAlertLow = "LOW STOCK",
    stockAlertOk = "IN STOCK",

    routeAreaManagement = "Routes & Sales Reps",
    addRouteBtn = "Add Route +",
    assignedRep = "Assigned Rep",
    assignedShops = "Assigned Retailers",
    pendingDeliveries = "Pending Deliveries",
    repPhone = "Phone",
    activeRepStatus = "Active on Route",

    thermalReceiptTitle = "Thermal Bluetooth Receipt (58mm/80mm)",
    printBluetooth = "Print Thermal Receipt",
    shareInvoice = "Share Digital Invoice",
    printingSimulation = "Sent ESC/POS payload to portable printer!",
    printerConnected = "BT-58D Portable Printer Ready",
    cashReceived = "Cash Received",
    changeAmount = "Balance Return",
    paymentMode = "Payment Mode",
    thankyouNote = "Thank you for your business! Please visit again.",
    taxVat = "VAT / Tax (0%)",
    subtotal = "Subtotal",
    discount = "Discount",
    grandTotal = "Grand Total",

    cancel = "Cancel",
    save = "Save & Record",
    close = "Close",
    selectCustomer = "Select Customer / Store",
    selectSupplier = "Select Supplier",
    selectProduct = "Select Product",
    quantity = "Quantity",
    rate = "Rate",
    addLineItem = "+ Add Item",
    currencySymbol = "৳"
)

val BengaliStrings = DistroStrings(
    appTitle = "ডিস্ট্রোমাস্টার",
    subtitle = "পাইকারি ও ডিস্ট্রিবিউশন",
    quickSync = "ক্লাউড সিঙ্ক",
    syncSuccess = "সব তথ্য সফলভাবে সিঙ্ক হয়েছে!",
    syncing = "ক্লাউডের সাথে সিঙ্ক হচ্ছে...",
    lastSynced = "এইমাত্র সিঙ্ক হয়েছে",

    navDashboard = "ড্যাশবোর্ড",
    navSales = "বিক্রি",
    navPurchase = "ক্রয়",
    navProducts = "পণ্য",
    navReports = "রিপোর্ট",

    totalSales = "মোট বিক্রি",
    vsLastMonth = "+১৪.৮% গত মাসের তুলনায়",
    customerDue = "গ্রাহক বকেয়া",
    supplierDue = "Supplier বকেয়া",
    salesReturn = "বিক্রিত পণ্য ফেরত",
    supplierReturn = "Supplier ফেরত",
    totalExpense = "মোট খরচ",
    currentStockValue = "বর্তমান স্টক মূল্য",
    quickShortcuts = "দ্রুত মেনু",
    recentInvoices = "সাম্প্রতিক চালানসমূহ",
    viewAll = "সব দেখুন",

    actionCustomer = "গ্রাহকগণ",
    actionSupplier = "সাপ্লায়ার",
    actionReturn = "পণ্য ফেরত",
    actionExpense = "খরচসমূহ",
    actionSales = "নতুন বিক্রি",
    actionPurchase = "পণ্য ক্রয়",
    actionProducts = "পণ্য তালিকা",
    actionReports = "রিপোর্ট",
    actionRoutes = "রুট ও এসআর",
    actionThermalPrinter = "থার্মাল রশিদ",

    salesAndBilling = "বিক্রি ও বিলিং ডিস্ট্রিবিউশন",
    newSaleBtn = "নতুন বিক্রি +",
    exportPdf = "পিডিএফ এক্সপোর্ট",
    searchSalePlaceholder = "চালান নম্বর, গ্রাহক বা ফোন নম্বর খুঁজুন...",
    filterAll = "সকল চালান",
    filterToday = "আজকের",
    filterThisMonth = "চলতি মাস",
    filterThisYear = "চলতি বছর",
    filterDue = "শুধু বকেয়া",
    filterPaid = "পরিশোধিত",
    invoiceNumber = "চালান নং",
    customerName = "দোকান / গ্রাহক",
    items = "আইটেম",
    totalAmount = "মোট টাকা",
    paidAmount = "জমা টাকা",
    dueAmount = "বকেয়া টাকা",
    invoiceCount = "মোট চালান",
    statusPaid = "পরিশোধ",
    statusDue = "বকেয়া",
    statusPartial = "আংশিক",

    deliveryStatus = "ডেলিভারি অবস্থা",
    stageTaken = "অর্ডার নেওয়া",
    stagePacked = "প্যাক করা",
    stageInTransit = "যাত্রাপথে",
    stageDelivered = "পৌঁছেছে",
    markNextDeliveryStage = "অবস্থা পরিবর্তন",

    purchaseManagement = "ক্রয় ও সাপ্লায়ার ব্যবস্থাপনা",
    newPurchaseBtn = "নতুন ক্রয় +",
    searchPurchasePlaceholder = "সাপ্লায়ার বা চালান খুঁজুন...",
    supplierName = "সাপ্লায়ার নাম",
    purchaseCount = "মোট ক্রয় সংখ্যা",

    productInventory = "পণ্য ও স্টক ইনভেন্টরি",
    addProductBtn = "পণ্য যোগ +",
    searchProductPlaceholder = "পণ্যের নাম বা বারকোড খুঁজুন...",
    filterHighStock = "বেশি স্টক",
    filterLowStock = "কম স্টক",
    filterOnlyLow = "শুধু ঝুঁকিপূর্ণ",
    totalProducts = "মোট আইটেম",
    stockQuantity = "মোট স্টক সংখ্যা",
    totalBuyValue = "মোট ক্রয়মূল্য",
    totalSaleValue = "মোট বিক্রয়মূল্য",
    skuBarcode = "এসকেইউ / বারকোড",
    unit = "একক",
    buyPrice = "ক্রয় রেট",
    sellPrice = "বিক্রয় রেট",
    margin = "মুনাফা",
    stockAlertLow = "কম স্টক!",
    stockAlertOk = "স্টকে আছে",

    routeAreaManagement = "রুট ও সেলস রিপ্রেজেন্টেটিভ",
    addRouteBtn = "নতুন রুট +",
    assignedRep = "দায়িত্বপ্রাপ্ত এসআর",
    assignedShops = "দোকান সংখ্যা",
    pendingDeliveries = "অপেক্ষমাণ ডেলিভারি",
    repPhone = "ফোন নম্বর",
    activeRepStatus = "রুটে সক্রিয়",

    thermalReceiptTitle = "ব্লুটুথ থার্মাল রশিদ (৫৮মিমি/৮০মিমি)",
    printBluetooth = "থার্মাল প্রিন্ট করুন",
    shareInvoice = "ডিজিটাল চালান পাঠান",
    printingSimulation = "পোর্টেবল প্রিন্টারে ESC/POS প্রিন্ট সফল!",
    printerConnected = "BT-58D পোর্টেবল প্রিন্টার প্রস্তুত",
    cashReceived = "নগদ গ্রহণ",
    changeAmount = "ফেরত টাকা",
    paymentMode = "পেমেন্ট মাধ্যম",
    thankyouNote = "আমাদের সাথে ব্যবসা করার জন্য ধন্যবাদ! আবার আসবেন।",
    taxVat = "ভ্যাট / ট্যাক্স (০%)",
    subtotal = "সাবটোটাল",
    discount = "ছাড়",
    grandTotal = "সর্বমোট বিল",

    cancel = "বাতিল",
    save = "সংরক্ষণ করুন",
    close = "বন্ধ করুন",
    selectCustomer = "দোকান / গ্রাহক নির্বাচন",
    selectSupplier = "সাপ্লায়ার নির্বাচন",
    selectProduct = "পণ্য নির্বাচন",
    quantity = "পরিমাণ",
    rate = "দর",
    addLineItem = "+ আইটেম যোগ করুন",
    currencySymbol = "৳"
)
